title:              Intellignet Science and Design
email:              a.r.mofayezi@gmail.com
description:        Welcome to the realms of Science, Culture and Art!
subdescription:     Intelligent Science and Design Foundation
author:             Ahmadreza Mofayezi
baseurl:            "/"
url:                "https://isdmo.github.io"

# Social Profiles
twitter_username:   isdmofayezi
github_username:    
facebook_username:  
instagram_username:  
linkedin_username: ahmadreza-mofayezi

# Add your google-analytics ID here to activate google analytics
google_analytics:   = # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
