title:              Intelligent Science and Design
email:              isdfoundation.mo@gmail.com
description:        Welcome to the realms of Science, Culture and Art!
subdescription:     Intelligent Science and Design Foundation
author:             Intelligent Science and Design Foundation
baseurl:            "/"
url:                "https://isdmo.github.io"

# Social Profiles
# twitter_username:   isdmofayezi
github_username:    
facebook_username:  
instagram_username:
youtube_username:  isdfoundation
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   = # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
